name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit:
    name: Unit and functional tests - PHP ${{ matrix.php }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: ['8.0', '8.1']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zip

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          args: --ignore-platform-req=ext-zip

      - name: Run PHPUnit unit tests
        run: composer test-unit

      - name: Run PHPUnit functional tests
        run: composer test-functional

  integration:
    name: Integration tests - PHP ${{ matrix.php }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: ['8.1']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zip

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          args: --ignore-platform-req=ext-zip

      - name: Setup integration environment
        run: |
          composer image-integration-prepare
          composer image-integration-start

      - name: Run tests
        run: composer test-integration
